server {
    listen 80;
    server_name h2faid.me www.h2faid.me;

    root /usr/share/nginx/html;
    index index.html;

    absolute_redirect off;

    location / {
        try_files $uri $uri/ =404;
    }
}